vehicle:
  robot_name: cpu_mid360_vehicle
  map_frame: map
  odom_frame: odom
  base_frame: base_footprint
  chassis_frame: chassis
  lidar_frame: livox_frame
  lidar_topic: /livox/lidar
  imu_topic: /livox/imu
  footprint:
    - [0.21, 0.195]
    - [0.21, -0.195]
    - [-0.21, -0.195]
    - [-0.21, 0.195]
  base_to_chassis:
    xyz: [0.0, 0.0, 0.12]
    rpy: [0.0, 0.0, 0.0]
  chassis_to_lidar:
    xyz: [0.35, 0.0, 0.18]
    rpy: [0.0, 0.0, 0.0]
  fast_lio:
    lidar_type: 1
    scan_line: 4
    blind: 0.5
    timestamp_unit: 3
    extrinsic_T: [-0.011, -0.02329, 0.04412]
    extrinsic_R:
      - 1.0
      - 0.0
      - 0.0
      - 0.0
      - 1.0
      - 0.0
      - 0.0
      - 0.0
      - 1.0
  humanoid_localization:
    base_frame: base_footprint
    imu_frame: livox_frame
    motion_frame: chassis
    input_odometry_topic: /Odometry_loc
    input_cloud_topic: /cloud_registered_1
    map_points_topic: /humanoid_loc/map_points
    submap_topic: /humanoid_loc/submap
    scan_points_topic: /humanoid_loc/scan_points
    scan2map_topic: /humanoid_loc/scan2map
    pcd_queue_maxsize: 10
    voxelsize_coarse: 0.01
    voxelsize_fine: 0.2
    threshold_fitness: 0.5
    threshold_fitness_init: 0.5
    loc_frequence: 2.5
    save_scan: false
    save_scan_path: /tmp/open3d_loc_scan_submap/
    hidden_removal: false
    maxpoints_source: 80000
    maxpoints_target: 400000
    filter_odom2map: false
    kalman_processVar2: 0.001
    kalman_estimatedMeasVar2: 0.02
    confidence_loc_th: 0.7
    dis_updatemap: 3.5
  pointcloud_to_laserscan:
    target_frame: livox_frame
    min_height: 0.2
    max_height: 1.0
  slam_toolbox:
    min_laser_range: 0.45
    max_laser_range: 40.0
